services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morefixes_app
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgrescvedumper
      POSTGRES_PASSWORD: a42a18537d74c3b7e584c769152c3d
      POSTGRES_DB: postgrescvedumper
    volumes:
      - ./:/app
    command: ["bash", "/app/Code/run.sh"]
